//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza.Frontend.Kunde.PizzaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PizzaEntity", Namespace="http://schemas.datacontract.org/2004/07/Pizza.Backend")]
    [System.SerializableAttribute()]
    public partial class PizzaEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PreisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZutatenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preis {
            get {
                return this.PreisField;
            }
            set {
                if ((this.PreisField.Equals(value) != true)) {
                    this.PreisField = value;
                    this.RaisePropertyChanged("Preis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zutaten {
            get {
                return this.ZutatenField;
            }
            set {
                if ((object.ReferenceEquals(this.ZutatenField, value) != true)) {
                    this.ZutatenField = value;
                    this.RaisePropertyChanged("Zutaten");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestellungEntity", Namespace="http://schemas.datacontract.org/2004/07/Pizza.Backend")]
    [System.SerializableAttribute()]
    public partial class BestellungEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BestellerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pizza.Frontend.Kunde.PizzaService.BestellungPositionEntity[] PizzenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Besteller {
            get {
                return this.BestellerField;
            }
            set {
                if ((object.ReferenceEquals(this.BestellerField, value) != true)) {
                    this.BestellerField = value;
                    this.RaisePropertyChanged("Besteller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Datum {
            get {
                return this.DatumField;
            }
            set {
                if ((this.DatumField.Equals(value) != true)) {
                    this.DatumField = value;
                    this.RaisePropertyChanged("Datum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pizza.Frontend.Kunde.PizzaService.BestellungPositionEntity[] Pizzen {
            get {
                return this.PizzenField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzenField, value) != true)) {
                    this.PizzenField = value;
                    this.RaisePropertyChanged("Pizzen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BestellungPositionEntity", Namespace="http://schemas.datacontract.org/2004/07/Pizza.Backend")]
    [System.SerializableAttribute()]
    public partial class BestellungPositionEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Pizza.Frontend.Kunde.PizzaService.PizzaEntity PizzaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Pizza.Frontend.Kunde.PizzaService.PizzaEntity Pizza {
            get {
                return this.PizzaField;
            }
            set {
                if ((object.ReferenceEquals(this.PizzaField, value) != true)) {
                    this.PizzaField = value;
                    this.RaisePropertyChanged("Pizza");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PizzaService.PizzaService")]
    public interface PizzaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Pizzen", ReplyAction="http://tempuri.org/PizzaService/PizzenResponse")]
        Pizza.Frontend.Kunde.PizzaService.PizzaEntity[] Pizzen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Pizzen", ReplyAction="http://tempuri.org/PizzaService/PizzenResponse")]
        System.Threading.Tasks.Task<Pizza.Frontend.Kunde.PizzaService.PizzaEntity[]> PizzenAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Speichern", ReplyAction="http://tempuri.org/PizzaService/SpeichernResponse")]
        void Speichern(Pizza.Frontend.Kunde.PizzaService.PizzaEntity pizza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Speichern", ReplyAction="http://tempuri.org/PizzaService/SpeichernResponse")]
        System.Threading.Tasks.Task SpeichernAsync(Pizza.Frontend.Kunde.PizzaService.PizzaEntity pizza);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Bestellen", ReplyAction="http://tempuri.org/PizzaService/BestellenResponse")]
        void Bestellen(string besteller, Pizza.Frontend.Kunde.PizzaService.PizzaEntity[] pizzen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Bestellen", ReplyAction="http://tempuri.org/PizzaService/BestellenResponse")]
        System.Threading.Tasks.Task BestellenAsync(string besteller, Pizza.Frontend.Kunde.PizzaService.PizzaEntity[] pizzen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Bestellungen", ReplyAction="http://tempuri.org/PizzaService/BestellungenResponse")]
        Pizza.Frontend.Kunde.PizzaService.BestellungEntity[] Bestellungen(string von);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/Bestellungen", ReplyAction="http://tempuri.org/PizzaService/BestellungenResponse")]
        System.Threading.Tasks.Task<Pizza.Frontend.Kunde.PizzaService.BestellungEntity[]> BestellungenAsync(string von);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/AlleBestellungen", ReplyAction="http://tempuri.org/PizzaService/AlleBestellungenResponse")]
        Pizza.Frontend.Kunde.PizzaService.BestellungEntity[] AlleBestellungen();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PizzaService/AlleBestellungen", ReplyAction="http://tempuri.org/PizzaService/AlleBestellungenResponse")]
        System.Threading.Tasks.Task<Pizza.Frontend.Kunde.PizzaService.BestellungEntity[]> AlleBestellungenAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PizzaServiceChannel : Pizza.Frontend.Kunde.PizzaService.PizzaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PizzaServiceClient : System.ServiceModel.ClientBase<Pizza.Frontend.Kunde.PizzaService.PizzaService>, Pizza.Frontend.Kunde.PizzaService.PizzaService {
        
        public PizzaServiceClient() {
        }
        
        public PizzaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PizzaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PizzaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Pizza.Frontend.Kunde.PizzaService.PizzaEntity[] Pizzen() {
            return base.Channel.Pizzen();
        }
        
        public System.Threading.Tasks.Task<Pizza.Frontend.Kunde.PizzaService.PizzaEntity[]> PizzenAsync() {
            return base.Channel.PizzenAsync();
        }
        
        public void Speichern(Pizza.Frontend.Kunde.PizzaService.PizzaEntity pizza) {
            base.Channel.Speichern(pizza);
        }
        
        public System.Threading.Tasks.Task SpeichernAsync(Pizza.Frontend.Kunde.PizzaService.PizzaEntity pizza) {
            return base.Channel.SpeichernAsync(pizza);
        }
        
        public void Bestellen(string besteller, Pizza.Frontend.Kunde.PizzaService.PizzaEntity[] pizzen) {
            base.Channel.Bestellen(besteller, pizzen);
        }
        
        public System.Threading.Tasks.Task BestellenAsync(string besteller, Pizza.Frontend.Kunde.PizzaService.PizzaEntity[] pizzen) {
            return base.Channel.BestellenAsync(besteller, pizzen);
        }
        
        public Pizza.Frontend.Kunde.PizzaService.BestellungEntity[] Bestellungen(string von) {
            return base.Channel.Bestellungen(von);
        }
        
        public System.Threading.Tasks.Task<Pizza.Frontend.Kunde.PizzaService.BestellungEntity[]> BestellungenAsync(string von) {
            return base.Channel.BestellungenAsync(von);
        }
        
        public Pizza.Frontend.Kunde.PizzaService.BestellungEntity[] AlleBestellungen() {
            return base.Channel.AlleBestellungen();
        }
        
        public System.Threading.Tasks.Task<Pizza.Frontend.Kunde.PizzaService.BestellungEntity[]> AlleBestellungenAsync() {
            return base.Channel.AlleBestellungenAsync();
        }
    }
}
